name: STM32 CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build STM32
      run: |
        cd Debug
        make clean
        make

    - name: Make flash script executable
      run: chmod +x flash.sh

    - name: Flash STM32
      run: ./flash.sh
